### ISSUE TITLE
get a exception when init Font() with file name

### ISSUE THREAD

**Issue by luckymore** [ArtifexSoftware/mupdf.js#122]
I follow the doc [here](https://mupdfjs.readthedocs.io/en/latest/classes/Font.html#Font)
```js
import * as mupdfjs from 'mupdf'
import path from 'path'

console.log(mupdfjs)
const font = new mupdfjs.Font(path.resolve('./public/AKNTFL+CMBX10.ttf'))
console.log(font)
```
Then, mupdfjs consoled, and get an error below:
```
Error: cannot find builtin font with name '/Users/zhangningning/Documents/github/mupdf.js/examples/vue/public/AKNTFL+CMBX10.ttf'
    at 5735545 (file:///Users/zhangningning/Documents/github/mupdf.js/examples/vue/node_modules/mupdf/dist/mupdf-wasm.js:995:27)
    at runEmAsmFunction (file:///Users/zhangningning/Documents/github/mupdf.js/examples/vue/node_modules/mupdf/dist/mupdf-wasm.js:4272:30)
    at _emscripten_asm_const_int (file:///Users/zhangningning/Documents/github/mupdf.js/examples/vue/node_modules/mupdf/dist/mupdf-wasm.js:4275:14)
    at wasm://wasm/023c430a:wasm-function[111]:0x8286
    at invoke_vi (file:///Users/zhangningning/Documents/github/mupdf.js/examples/vue/node_modules/mupdf/dist/mupdf-wasm.js:5713:29)
    at wasm://wasm/023c430a:wasm-function[259]:0xf172
    at Object._wasm_new_base14_font (file:///Users/zhangningning/Documents/github/mupdf.js/examples/vue/node_modules/mupdf/dist/mupdf-wasm.js:705:12)
    at new Font (file:///Users/zhangningning/Documents/github/mupdf.js/examples/vue/node_modules/mupdf/dist/mupdf.js:520:36)
    at file:///Users/zhangningning/Documents/github/mupdf.js/examples/vue/test.mjs:5:14
```
Node.js v22.1.0
mupdf.js 1.0.0

**Comment by jamie-lemon** [comment]
I would try the following to load a font:

```
import * as fs from "fs"

let font_buffer = fs.readFileSync("./public/AKNTFL+CMBX10.ttf")
const font = await new mupdfjs.Font('name-of-your-font', font_buffer)
console.log("font="+font.getName())
```

This is because only the built in fonts can be constructed with just a string. You need to use a different method where you supply the font buffer data. My mistake in the documentation - I will update the documentation to include the other constructor methods for Font.

Having said this we have a related problem with using fonts, so you may run into this issue too:

https://github.com/ArtifexSoftware/mupdf.js/issues/120

**Comment by luckymore** [comment]
I have tried this, but get `false`.

```js
import * as fs from "fs"
import * as mupdfjs from 'mupdf'

let font_buffer = fs.readFileSync("./public/8aeac737-de2d-42ce-8db1-d8641c14d579")
const font = await new mupdfjs.Font('name-of-your-font', font_buffer)
console.log(font.isBold())
```

[fontfile](https://github.com/luckymore/N-blog/blob/master/public/8aeac737-de2d-42ce-8db1-d8641c14d579)

**Comment by jamie-lemon** [comment]
@luckymore  The font file doesn't look like a font file to me?

**Comment by luckymore** [comment]
add file ext `.otf` is ok, look this please

[fontfile](https://github.com/luckymore/N-blog/blob/master/public/8aeac737-de2d-42ce-8db1-d8641c14d579.otf)
