### ISSUE TITLE
DocumentWriter.close WASM RuntimeError

### ISSUE THREAD

**Issue by RythenGlyth** [ArtifexSoftware/mupdf.js#54]
The `DocumentWriter.close` function seems malfunction and throws WASM RuntimeError.

This is the code reduced to the minimum:
```js
import * as mupdf from 'mupdf'

const outBuffer = new mupdf.Buffer()
const out = new mupdf.DocumentWriter(outBuffer, ".pdf", "")
out.close()
```

It throws the following error
```
wasm://wasm/0239b566:1


RuntimeError: null function or function signature mismatch
    at wasm://wasm/0239b566:wasm-function[1894]:0x13ff94
    at wasm://wasm/0239b566:wasm-function[1893]:0x13ff49
    at wasm://wasm/0239b566:wasm-function[1985]:0x147d8e
    at wasm://wasm/0239b566:wasm-function[1895]:0x13fff1
    at wasm://wasm/0239b566:wasm-function[3558]:0x2669f9
    at invoke_viiii (file:///.../node_modules/mupdf/dist/mupdf-wasm.js:5784:29)
    at wasm://wasm/0239b566:wasm-function[3548]:0x25ff90
    at wasm://wasm/0239b566:wasm-function[3546]:0x25c738
    at wasm://wasm/0239b566:wasm-function[3567]:0x26cc49
    at wasm://wasm/0239b566:wasm-function[2299]:0x1797b5

Node.js v21.6.2
```

instead if I try to add a page:
```js
import * as mupdf from 'mupdf'

const outBuffer = new mupdf.Buffer()
const out = new mupdf.DocumentWriter(outBuffer, ".pdf", "")
const dev = out.beginPage([0,0,200,200])
/* draw something on the Device or not, it doesn't matter */
out.endPage()
out.close()
```

another error is thrown:
```
wasm://wasm/0239b566:1


RuntimeError: memory access out of bounds
    at wasm://wasm/0239b566:wasm-function[1894]:0x13ffad
    at wasm://wasm/0239b566:wasm-function[1893]:0x13ff49
    at wasm://wasm/0239b566:wasm-function[1985]:0x147ecf
    at wasm://wasm/0239b566:wasm-function[1895]:0x13fff1
    at wasm://wasm/0239b566:wasm-function[3558]:0x2669f9
    at invoke_viiii (file:///.../node_modules/mupdf/dist/mupdf-wasm.js:5784:29)
    at wasm://wasm/0239b566:wasm-function[3548]:0x25ff90
    at wasm://wasm/0239b566:wasm-function[3546]:0x25c738
    at wasm://wasm/0239b566:wasm-function[3567]:0x26cc49
    at wasm://wasm/0239b566:wasm-function[2299]:0x1797b5
    
Node.js v21.6.2
```

No matter what, `outBuffer.getLength()` is always 0 after the `out.close()`

When recreating everything from mupdf's `muconvert.c` in JS, the second error is thrown as well.

**Comment by jamie-lemon** [comment]
Interesting, I get a different error output on your first example as follows:
```
5735101: ($0) => { throw new Error(UTF8ToString($0)); },  
                          ^
Error: unknown output document format: 
    at 5735101 (file:///artifex/SDK/mupdfjs/npm-0.2.0/node_modules/mupdf/dist/mupdf-wasm.js:995:27)
    at runEmAsmFunction (file:///artifex/SDK/mupdfjs/npm-0.2.0/node_modules/mupdf/dist/mupdf-wasm.js:4256:30)
    at _emscripten_asm_const_int (file:///artifex/SDK/mupdfjs/npm-0.2.0/node_modules/mupdf/dist/mupdf-wasm.js:4259:14)
    at wasm://wasm/0239b566:wasm-function[111]:0x802a
    at invoke_vi (file:///artifex/SDK/mupdfjs/npm-0.2.0/node_modules/mupdf/dist/mupdf-wasm.js:5685:29)
    at wasm://wasm/0239b566:wasm-function[325]:0x2d502
    at Object._wasm_new_document_writer_with_buffer (file:///artifex/SDK/mupdfjs/npm-0.2.0/node_modules/mupdf/dist/mupdf-wasm.js:705:12)
    at new DocumentWriter (file:///artifex/SDK/mupdfjs/npm-0.2.0/node_modules/mupdf/dist/mupdf.js:1136:24)
    at file:///artifex/SDK/mupdfjs/npm-0.2.0/node.mjs:4:13

Node.js v20.8.0
```

**Comment by RythenGlyth** [comment]
That's really strange.
I used the 0.2.0 npm version as you did if I interpret your error stack correctly. (I also compiled my own version of this package and it threw the same errors)

What does differ is the node version and maybe the OS? I ran mine on Windows

**Comment by jamie-lemon** [comment]
Okay - I aligned as much as possible with you and updated my node to v21.6.2 - I still get the same error. I am on a MacOS so this probably explains the difference in our output logs. I am also just using the mupdf.js from NPM directly. I think we will have to wait until next week to figure this out as the main developer @ccxvii will be available then.

**Comment by RythenGlyth** [comment]
Okay, thank you

**Comment by jamie-lemon** [comment]
@RythenGlyth This should be fixed with the latest release of mupdf.js (0.2.1) on NPM - https://www.npmjs.com/package/mupdf , please confirm!

**Comment by RythenGlyth** [comment]
Yes it does perfectly work. Thank you!
